### ISSUE TITLE
Individual zone cleaning

### ISSUE THREAD

**Issue by DaveM8686** [bwp91/homebridge-deebot#16] opened 2021-03-21 22:54 UTC
* **Please explain your feature request in a one or two sentences.**
I'd like to be able to clean individual zones through HK, if possible, for Deebots that let you name the zone.  For example, the Ozmo 920 lets you name each area as Kitchen, Lounge, Laundry, etc.  I'm thinking this could be accomplished by having a switch per zone appear, where you can toggle several switches to only clean those zones.

* **Is your feature request related to a problem? Please describe.**

No problem, just a case of reducing the need to still mostly rely on the native Ecovacs app.

* **Any particular ECOVACS devices that this relates to?**

Ozmo 920, Ozmo 950, U2

* **Anything else?**

Thanks for the great work so far!

**Comment by bwp91** [comment] 2021-04-07 11:02
Hi @DaveM8686 

Sorry it's taken me a while to get back to you on this.
I've been going back and fourth on this idea for a few days (well, since you posted this idea!)

The reason being... this is something that the other deebot plugin already provides (homebridge-deebotEcovacs), if you look into the plugin's [configurable options](https://github.com/nicoduj/homebridge-deebotEcovacs#homebridge-configuration) in particular the `publishCustomAreaSwitches` option.

My aim for this plugin has always been to keep it as simple as possible, without venturing too far into the extra options that the other plugin provides.

Have you checked out the other plugin for this feature?

Thanks

**Comment by bwp91** [comment] 2021-04-07 11:05
Either way, I'm not sure if it is possible to turn on a range of switches so the device cleans multiple areas in one go... I think it would always need to be one area at a time (in principle, one switch turns the rest off). 

@mrbungle64 would be the best person to elaborate on this!

**Comment by mrbungle64** [comment] 2021-04-07 16:28
@bwp91 

> Either way, I'm not sure if it is possible to turn on a range of switches so the device cleans multiple areas in one go... I think it would always need to be one area at a time (in principle, one switch turns the rest off).

As far as I know, the behavior of HomeKit is exactly as you described. For vacuum cleaners, the possibilities seem to be very limited, as there is no official support for this class of devices yet. That's why I don't use it much yet.

> 
> @mrbungle64 would be the best person to elaborate on this!

The library is capable of cleaning the areas separately and also multiple spot areas at a time.
The homebridge-deebotEcovacs plugin uses it to be able to clean the user-defined areas (`publishCustomAreaSwitches`) separately (as you already mentioned above)

@DaveM8686 
Are you running 3 devices (Ozmo 920, Ozmo 950, U2)?

**Comment by DaveM8686** [comment] 2021-04-07 22:50
@mrbungle64 sorry for the confusion, I'm not running all three, just the 920.  The other two are just other models that I know let you have the areas.

@bwp91 thanks for the clarification, and I totally understand wanting to keep this simple.  I was using the other plugin originally, but found it quite complicated (I really just wanted a simple on/off originally, and don't like that it displays the vacuum as a fan).

While you're both here, it might be worth pointing out that I was also going to use this as a workaround for the fact that triggering the cleaning through HomeKit seems to reset my map each time, but maybe now I'll raise that as a new issue (unless you're ok with it being on here?).

**Comment by mrbungle64** [comment] 2021-04-08 11:00
@DaveM8686 

> While you're both here, it might be worth pointing out that I was also going to use this as a workaround for the fact that triggering the cleaning through HomeKit seems to reset my map each time, but maybe now I'll raise that as a new issue (unless you're ok with it being on here?).

What do you mean?

**Comment by bwp91** [comment] 2021-04-08 16:22
@DaveM8686 do you have “spot areas” defined in the ecovacs app? my device doesn’t support this so I don’t know what the UI looks like, but are they numbered like 0,1,2,3…?

**Comment by mrbungle64** [comment] 2021-04-08 16:40
> @DaveM8686 do you have “spot areas” defined in the ecovacs app? my device doesn’t support this so I don’t know what the UI looks like, but are they numbered like 0,1,2,3…?

@bwp91 
Unfortunately, the spot areas are not numbered in the App. You can only choose between "standard (A, B, C ...)" and predefined naming (e.g. "Living room", "kitchen").

You can find some information on how to retrieve the data in the library's wiki:
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Map-data

**Comment by DaveM8686** [comment] 2021-04-08 22:35
> 
> 
> @DaveM8686
> 
> > While you're both here, it might be worth pointing out that I was also going to use this as a workaround for the fact that triggering the cleaning through HomeKit seems to reset my map each time, but maybe now I'll raise that as a new issue (unless you're ok with it being on here?).
> 
> What do you mean?

So basically, when I run the Deebot through the native app for the first time, it creates a map.  From there I can edit that map to cut it into rooms and give each room a label.  When I run it again, that maps stays how it is.  But, when I run it through HomeKit using this plugin, it's like it resets the map.  It still keeps the general outline of it, but all the rooms I've split and labelled get reset to how they were when it first did its mapping.  I've tried it twice to confirm it's definitely running through HK that causes this.

**Comment by mrbungle64** [comment] 2021-04-08 22:44
@DaveM8686 

> > @DaveM8686
> > > While you're both here, it might be worth pointing out that I was also going to use this as a workaround for the fact that triggering the cleaning through HomeKit seems to reset my map each time, but maybe now I'll raise that as a new issue (unless you're ok with it being on here?).
> > 
> > 
> > What do you mean?
> 
> So basically, when I run the Deebot through the native app for the first time, it creates a map. From there I can edit that map to cut it into rooms and give each room a label. When I run it again, that maps stays how it is. But, when I run it through HomeKit using this plugin, it's like it resets the map. It still keeps the general outline of it, but all the rooms I've split and labelled get reset to how they were when it first did its mapping. I've tried it twice to confirm it's definitely running through HK that causes this.

It is almost impossible that this is caused by the plugin, since it does not use any functions that modify data of the map.

**Comment by DaveM8686** [comment] 2021-04-08 22:54
> 
> 
> > @DaveM8686 do you have “spot areas” defined in the ecovacs app? my device doesn’t support this so I don’t know what the UI looks like, but are they numbered like 0,1,2,3…?
> 
> @bwp91
> Unfortunately, the spot areas are not numbered in the App. You can only choose between "standard (A, B, C ...)" and predefined naming (e.g. "Living room", "kitchen").
> 
> You can find some information on how to retrieve the data in the library's wiki:
> https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Map-data

I'm so confused by this, sorry.  Do I need to run this code to find out what number area is what I've called Kitchen or whatever?

**Comment by mrbungle64** [comment] 2021-04-08 22:56
> > > @DaveM8686 do you have “spot areas” defined in the ecovacs app? my device doesn’t support this so I don’t know what the UI looks like, but are they numbered like 0,1,2,3…?
> > 
> > 
> > @bwp91
> > Unfortunately, the spot areas are not numbered in the App. You can only choose between "standard (A, B, C ...)" and predefined naming (e.g. "Living room", "kitchen").
> > You can find some information on how to retrieve the data in the library's wiki:
> > https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Map-data
> 
> I'm so confused by this, sorry. Do I need to run this code to find out what number area is what I've called Kitchen or whatever?

No, this is information for @bwp91

**Comment by DaveM8686** [comment] 2021-04-08 23:29
Ah, ok thanks.  I'm playing around with the other plugin now.  It's changed a LOT since the last time I used it, which is good.  Just trying to figure out how to get the coordinates for custom areas now.  I see there's a few different issues with people doing the same thing, so hopefully the answer is buried in there somewhere.

Regarding the map being changed, not sure what to say.  I set up the map originally, ran it through the Ecovacs app for a week with no problem, ran it through HK once and it all got changed.  Reset the map, did the same thing, verified the same result.

Thanks for your help, both of you, by the way.

**Comment by bwp91** [comment] 2021-04-09 07:01
The only way I can see perhaps adding this to this plugin would be via the Eve app rather than Home app. I don't want to clutter the screen with endless amounts of switches, it's not great for the UI as sometimes the Home app can already feel quite clunky.

So it would be using a custom characteristic called 'Clean Area' that would only appears in the Eve app, would look something like this:

![IMG_5067](https://user-images.githubusercontent.com/43026681/114141048-fdb1ad00-9908-11eb-896b-369d90723418.PNG)

The possible clean areas (0-9) or (1-10) for example could then be mapped via the configuration to spot areas, for example:

```
0 => "0,1"
1 => "3"
2 => "3, 4, 5"
```

and then when the 'clean' switch is pressed it would clean the corresponding areas.

Unfortunately HomeKit is very limiting to what is possible outside its pre-defined services, so whilst this solution would work, it would involve using the Eve app and remembering which numbers correspond to which areas. You'd also need to somehow obtain your current SpotArea numerals using the `ecovacs-deebot` library outside of the plugin (I could help with this eventually).

You would then, however, be able to create Scenes via the Eve app to e.g. turn the cleaning area to 5 and turn the power on... once a scene has been made this would appear in the Home app.

This is a solution that could work, albeit not ideal, let me know what you'd think of this @DaveM8686

**Comment by DaveM8686** [comment] 2021-04-09 10:27
A clever solution, but I think you were right in the beginning. The point of this app was to keep it simple, and for what I'm after, I should be using the other app. In that case I'll leave this to you if you think it's worth spending any more time on. Thank you either way.

**Comment by bwp91** [comment] 2021-04-09 15:33
I think I'll leave it then in that case. Are you happy for me to close this issue? I hope you achieve what you want with the other plugin!

**Comment by DaveM8686** [comment] 2021-04-09 21:33
Yep, happy to close. Thanks again!

**Closed as completed** 2021-04-10 07:45 UTC
