### ISSUE TITLE
 getaddrinfo ENOTFOUND api-app.dc-ww.ww.ecouser.net

### ISSUE THREAD

**Issue by daragill** [bwp91/homebridge-deebot#131] opened 2023-03-11 10:57 UTC
### What issue do you have? Please be as thorough and explicit as possible.
Getting the following error:
```
[11/03/2023, 21:47:33] [deebot] ***** Disabling plugin. *****
[11/03/2023, 21:47:33] [deebot] ***** getaddrinfo ENOTFOUND api-app.dc-ww.ww.ecouser.net at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****
```

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
6.0

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Deebot T10

### Please paste any relevant logs below.

```
[11/03/2023, 21:53:14] [HB Supervisor] Restarting Homebridge...
[11/03/2023, 21:53:14] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[11/03/2023, 21:53:14] [HB Supervisor] Started Homebridge v1.6.0 with PID: 1319
[11/03/2023, 21:53:15] Loaded config.json with 0 accessories and 4 platforms.
[11/03/2023, 21:53:15] Loaded 1 cached accessories from cachedAccessories.
[11/03/2023, 21:53:15] ---
[11/03/2023, 21:53:15] Loaded plugin: homebridge-appletv-now-playing@0.3.6
[11/03/2023, 21:53:15] Registering platform 'homebridge-appletv-now-playing.AppleTvNowPlayingPlatform'
[11/03/2023, 21:53:15] ---
wasm streaming compile failed: TypeError [ERR_INVALID_ARG_TYPE]: The "source" argument must be an instance of Response or an Promise resolving to Response. Received type string ('AGFzbQEAAAABSQxgAX8AYAAB...)
falling back to ArrayBuffer instantiation
[11/03/2023, 21:53:16] Loaded plugin: homebridge-deebot@6.0.0
[11/03/2023, 21:53:16] Registering platform 'homebridge-deebot.Deebot'
[11/03/2023, 21:53:16] ---
[11/03/2023, 21:53:18] Loaded plugin: homebridge-hue@0.13.57
[11/03/2023, 21:53:18] Registering platform 'homebridge-hue.Hue'
[11/03/2023, 21:53:18] ---
[11/03/2023, 21:53:18] Loaded plugin: homebridge-plex-webhooks@2.2.0
[11/03/2023, 21:53:18] Registering platform 'homebridge-plex-webhooks.PlexWebhooks'
[11/03/2023, 21:53:18] ---
[11/03/2023, 21:53:18] Loading 4 platforms...
[11/03/2023, 21:53:18] [Hue Homebridge] Initializing Hue platform...
[11/03/2023, 21:53:18] [Hue Homebridge] homebridge-hue v0.13.57, node v18.15.0, homebridge v1.6.0
[11/03/2023, 21:53:18] [Hue Homebridge] warning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
[11/03/2023, 21:53:18] [Hue Homebridge] searching bridges and gateways
[11/03/2023, 21:53:18] [deebot] Initializing Deebot platform...
[11/03/2023, 21:53:18] [deebot] Initialising plugin v6.0.0 | System linux | Node v18.15.0 | HB v1.6.0 | HAPNodeJS v0.11.0...
[11/03/2023, 21:53:18] [Plex Webhooks Platform] Initializing PlexWebhooks platform...
[11/03/2023, 21:53:18] [deebot] Plugin initialised. Setting up accessories....
[11/03/2023, 21:53:18] [deebot] Using ecovacs-deebot library v0.9.3.
[11/03/2023, 21:53:18] [Plex Webhooks Platform] Found 1 accessory, Plex Playing in config.
[11/03/2023, 21:53:18] [Plex Webhooks Platform] Updating accessory [Plex Playing] (c353ee88-63ae-4081-a462-8cccd1d414d3)
[11/03/2023, 21:53:18] [Plex Webhooks Platform] Server is listening at http://192.168.68.94:32401
[11/03/2023, 21:53:19] [Hue Homebridge] meethue.com: request 1: GET /
[11/03/2023, 21:53:19] [Hue Homebridge] meethue.com: request 1: http status 429 Too Many Requests
[11/03/2023, 21:53:19] [Hue Homebridge] meethue.com: request 1: GET /
[11/03/2023, 21:53:19] [Hue Homebridge] meethue.com: request 1: http status 429 Too Many Requests
[11/03/2023, 21:53:20] [deebot] ***** Disabling plugin. *****
[11/03/2023, 21:53:20] [deebot] ***** getaddrinfo ENOTFOUND api-app.dc-ww.ww.ecouser.net at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****
[11/03/2023, 21:53:23] [Hue Homebridge] Philips hue: Signify Netherlands B.V. BSB002 bridge v1956046040, api v1.56.0
[11/03/2023, 21:53:24] [Hue Homebridge] Philips hue: 3 accessories
[11/03/2023, 21:53:24] [Hue Homebridge] masked debug info dumped to /var/lib/homebridge/homebridge-hue.json.gz
[11/03/2023, 21:53:24] Initializing platform accessory 'Philips hue'...
[11/03/2023, 21:53:24] [Hue Homebridge] Philips hue: 2 services
[11/03/2023, 21:53:24] Initializing platform accessory 'Kitchen Strip Light Left'...
[11/03/2023, 21:53:24] Initializing platform accessory 'Kitchen strip - Right'...
```

**Comment by mrbungle64** [comment] 2023-03-11 11:03
@daragill 

Please try other region than "ww".

**Comment by daragill** [comment] 2023-03-11 11:07
Thanks for the reply! My config code has it as AU?

```
  "name": "deebot",
            "countryCode": "AU",
            "username": "daragill@gmail.com",
            "password": "0405803379Dg1986",
            "platform": "Deebot",
            "refreshTime": 30
```

**Comment by daragill** [comment] 2023-03-11 11:08
Thanks for the reply! My config code has it set as AU:
```
  "name": "deebot",
            "countryCode": "AU",
            "username": "***",
            "password": "***",
            "platform": "Deebot",
            "refreshTime": 30
```

**Comment by mrbungle64** [comment] 2023-03-11 11:15
@daragill 

Ok, I see ... I already started to fix this in the library

cc: @bwp91

**Comment by daragill** [comment] 2023-03-11 11:20
@mrbungle64 

Thanks! When I set it to WW the error is there still but the WW disappears:

```
[11/03/2023, 22:17:34] [deebot] ***** Disabling plugin. *****
[11/03/2023, 22:17:34] [deebot] ***** getaddrinfo ENOTFOUND gl-ww-api.ecovacs.com at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****
```

**Comment by mrbungle64** [comment] 2023-03-11 11:29
@bwp91 

Please update to version 0.9.4-beta.0 of the library. Thanks

**Comment by mrbungle64** [comment] 2023-03-11 11:45
@daragill 

Is it working if you use an Asian country like "ID", "SG" or "PH"?

**Comment by daragill** [comment] 2023-03-11 12:04
@mrbungle64 

Yes! Have tested with ID and its working fine now.

**Comment by bwp91** [comment] 2023-03-14 21:17
@daragill closing this, glad this has been resolved

@mrbungle64 thanks for your input here (thanks as always!)

**Comment by mrbungle64** [comment] 2023-03-15 09:45
> @bwp91
> 
> Please update to version 0.9.4-beta.0 of the library. Thanks

@bwp91 

Can you please update to version 0.9.4-beta.0 of the library? 😉

**Comment by bwp91** [comment] 2023-03-18 03:45
hi @mrbungle64 sorry for delay, new beta available with 0.9.4 beta of your client

**Comment by mrbungle64** [comment] 2023-03-19 07:25
@daragill 

Can you please test if country code "AU" works again with the latest beta?

**Comment by daragill** [comment] 2023-03-19 10:11
@mrbungle64 

Have tested 6.0.2-beta and it's not working on AU

```

[37m[19/03/2023, 21:06:49] [39m[36m[deebot][39m [33m[OakBOT] sent error [DNS lookup failed: getaddrinfo ENOTFOUND api-app.dc-ww.ww.ecouser.net].[39m

```

**Comment by mrbungle64** [comment] 2023-03-19 11:22
@daragill 

Sorry, I checked for the wrong letter case 🙈 

@bwp91 Can you please update to 0.9.4-beta.1?

**Comment by bwp91** [comment] 2023-03-19 14:48
@mrbungle64 done - what exactly is the issue here? thinking of what i can do in the plugin to at least state what is happening

**Comment by mrbungle64** [comment] 2023-03-19 15:41
@bwp91 

> @mrbungle64 done

Thanks 👍🏻 

> what exactly is the issue here? thinking of what i can do in the plugin to at least state what is happening

I switched to a different API endpoint with version 0.9.3:
https://github.com/mrbungle64/ecovacs-deebot.js#093

The problem is, that countries with "continent" "WW" cannot use the this new API endpoint. It seems to be different for that countries.

With the old API endpoint many users (incl. me) had several timeout errors per day:
- https://github.com/mrbungle64/ecovacs-deebot.js/issues/303
- https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/412
- https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/432
- https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/439

That's why I switched to the new endpoint. It seems to be working fine so far (for most countries).

**Comment by mrbungle64** [comment] 2023-03-19 15:42
@daragill 

Can you please check it works with v6.0.2-beta.1 now (using country code "AU")?

**Comment by daragill** [comment] 2023-03-20 22:16
@mrbungle64 

This has been tested and its working with "AU"

Thanks!

**Comment by mrbungle64** [comment] 2023-03-20 22:31
> @mrbungle64
> 
> This has been tested and its working with "AU"
> 
> Thanks!

Great! Thank you as well 👍🏻

**Comment by bwp91** [comment] 2023-03-24 21:45
I'm assuming this has been fixed, so closing, please reopen if necessary.

I just released new version of the plugin.

**Closed as completed by bwp91** 2023-03-24 21:45 UTC
